name: Render Intro

on:
  workflow_dispatch:

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
        working-directory: ./remotion
      - run: echo $WORKFLOW_INPUT > input-props.json
        working-directory: ./remotion
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build -- --props="./input-props.json"
        working-directory: ./remotion
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: remotion/out/video.mp4
